version: '3'

services:
  myapp-backend:
    image: aminebensaid/bensaidmedamine:1.0.0
    ports:
      - "8081:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/MyDatabasePFE
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

  database:
    image: mypostgresimage
    environment:
      POSTGRES_DB: MyDatabasePFE
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus
    container_name: my-prometheus
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: my-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
